### PR TITLE
Toast bug fixes

### LINKED ISSUE #400: Verify email toast appears if a user verifies their email soon after signing up
Steps to reproduce:
1. Create new email account
2. Verify email via email link
3. (back on platform) Hit skip for now on get-extension screen

Result:
user sees verify email toast

### LINKED ISSUE #401: Privacy policy toast appears even after accepting policy
1. create new email account
2. Hit skip for now on get-extension screen
3. Accept privacy policy through the modal

Result:
Privacy policy toast is still displayed

### LINKED ISSUE #402: Hitting resend on verify email toast sometimes logs user out
1. create new email account
2. hit skip for now on get-extension screen
3. hit Resend on verify email toast

result:
email is sent as expected
user is sometime logged out, though

### LINKED ISSUE #403: Typo in Email resend confirmation box
"meail" should be "email"

Screen Shot 2022-10-13 at 12 53 55 PM

### LINKED ISSUE #405: "Reactivate" button shows when it's not supposed to
Steps:
1. Create a new account
2. Agree to the privacy policy
3. The first time you land on Home Page after accepting privacy policy, the "Reactivate" button is visible, but it shouldn't be. Upon refresh the button disappears

### PR DESCRIPTION
**Pull request by aaga**
Closes #400
Closes #401 
Closes #402 
Closes #403 
Closes #405 

@thomik-corp I changed the `isUserVerified` behavior because it turns out that `onAuthStateChanged` doesn't fire when the user verifies their email

@jepstein tagging you for review mainly so you can test out the flows for functionality

### CODE REVIEW

File: web-platform/website/src/services/AuthenticationService.tsx [hunk 1]
```diff
@@ -73,25 +72,13 @@ export async function getCurrentUser() {
...
-        Boolean(
-          firebaseUser &&
-            firebaseUser.providerData &&
-            firebaseUser.providerData.length &&
-            ((firebaseUser.providerData[0].providerId === "password" &&
-              firebaseUser.emailVerified) ||
-              firebaseUser.providerData[0].providerId === "google.com")
-        )
-      );
-
```
Comment (thomik-corp) [inline web-platform/website/src/services/AuthenticationService.tsx:94]: We can restore this file and then do just this:
```
onAuthStateChanged((auth, firebaseUser) => {
    // Refactor code in updateUserVerificationState
    updateUserVerificationState(firebaseUser);
});

useEffect(() => {
  (async () => {
       updateUserVerificationState(user && user.firebaseUser);
   })();
}, []); 
```

Comment (aaga) [reply web-platform/website/src/services/AuthenticationService.tsx:94]: I considered this, but I think it would be a bad pattern to have to always manually call `updateUserVerificationState` before looking at the value of `isUserVerified`.

Comment (aaga) [reply web-platform/website/src/services/AuthenticationService.tsx:94]: implemented the suggested change, and exported a `reloadUser` to manually trigger

File: web-platform/website/src/components/pages/studies/study-card/ToastComponent.tsx [hunk 2]
```diff
@@ -16,9 +16,10 @@ interface ToastProps {
   button: string;
   type: string;
   close?: string;
-  openModal?: () => void;
+  openEmailModal?: () => void;
```
Comment (thomik-corp) [inline web-platform/website/src/components/pages/studies/study-card/ToastComponent.tsx:19]: Why context specific name? Since this component is generic we should use generic names. We should also name this onOpenModal to better indicate it being a callback.

File: web-platform/website/src/services/AuthenticationService.tsx [hunk 3]
```diff
@@ -109,6 +112,13 @@ export function AuthenticationProvider(props: { children: React.ReactNode }) {
         isLoaded,
         isLoggingIn,
         isUserVerified,
+        reloadUser: async () => {
+          if (!user || !user.firebaseUser) {
+            return;
+          }
+          await user.firebaseUser.reload();
+          updateUserVerificationState(user.firebaseUser);
+        },
```
Comment (thomik-corp) [inline web-platform/website/src/services/AuthenticationService.tsx:121]: We can keep this private in this file and do it within useEffect(() => {}, []). Ideally this should only be done once at the first load.

Comment (aaga) [reply web-platform/website/src/services/AuthenticationService.tsx:121]: AFAICT this doesn't work because useEffect does not run when user clicks "Skip for now" on the get extension screen. We need to expose some way to manually refresh the user.

Ideally "onAuthStateChanged" would fire when the user verifies their email (which would avoid all this) but that is not the case (and lots of people on StackOverflow have complained about it)

File: web-platform/website/src/components/pages/studies/ProductToasts.tsx [hunk 4]
```diff
@@ -25,30 +25,47 @@ export function ProductToasts() {
...
+  const { user, isUserVerified, reloadUser } = useAuthentication();
+  const { installedStudyIds, rallyExtensionStudy } = useStudies();
   const { userDocument } = useUserDocument();
 
   useEffect(() => {
-    if (user && user.firebaseUser && !isUserVerified) {
-      setShowEmailNotVerifiedToast(true);
+    if (!reloadUser) {
+      return;
     }
```
Comment (thomik-corp) [inline web-platform/website/src/components/pages/studies/ProductToasts.tsx:35]: reloadUser should never be null correct? So we can remove this.

File: web-platform/website/src/components/pages/studies/study-card/ToastComponent.tsx [hunk 5]
```diff
@@ -65,10 +68,20 @@ export function ToastComponent({
...
+                if (type === strings.verifyEmail.type) {
+                  try {
+                    await sendEmailVerification();
+                  } catch (e) {
+                    console.error(
+                      "Error when trying to resend email verification:",
+                      e
+                    );
+                  }
+                  (onOpenModal as () => void)();
```
Comment (thomik-corp) [inline web-platform/website/src/components/pages/studies/study-card/ToastComponent.tsx:80]: This is where we are breaking generic nature of this component. ToastComponent is supposed to represent a generic toast and adding email verification does not make sense here. This should be done in onOpenModal from ProductToasts IMO.

**Review by thomik-corp — APPROVED** [review]
