### PR TITLE
button bugs fix

### LINKED ISSUE #468: "Add the extension" button on "Get Extension" page requires clicking on text
Looks like a similar issue as #439, on the dedicated interstitial "Get Extension" page:

https://members.rally.mozilla.org/get-extension

image

Hovering over the text underlines and it now works:

image

Clicking anywhere on the button outside of the text "Add the Extension" does nothing:

image

### LINKED ISSUE #470: "Create Profile" button on "Tell us about yourself" dialog requires clicking on text
Looks similar to https://github.com/mozilla-rally/rally/issues/468 and https://github.com/mozilla-rally/rally/issues/439.

image

### PR DESCRIPTION
**Pull request by Carla-Moz**
This PR addressed some button bugs on the add extension page and survey card on the home page.

closes #470 
closes #468

### CODE REVIEW

File: web-platform/website/src/components/pages/get-extension/GetExtensionView.tsx [hunk 1]
```diff
@@ -72,20 +72,19 @@ export function GetExtensionView() {
...
-                onClick={() => {
-                  router.push("/");
-                }}
-              >
-                {strings.getExt}
-              </a>
-            )}
+          <LoginButton
+            onClick={() => {
+              allStudies &&
```
Comment (aaga) [inline web-platform/website/src/components/pages/get-extension/GetExtensionView.tsx:77]: IMO this `allStudies` check should live outside the button; i.e. the button shouldn't appear at all until `allStudies` has loaded.

I think this can be accomplished with something like:
```
{allStudies && <LoginButton>...</LoginButton>}
```

**Review by aaga — CHANGES_REQUESTED** [review]
mostly lgtm! minor change request

also the `LinkStyles` import can be removed on line 12 in `GetExtensionView.tsx`

**Review by jepstein — COMMENTED** [review]
works as expected

**Comment by Carla-Moz** [comment]
> mostly lgtm! minor change request
> 
> also the `LinkStyles` import can be removed on line 12 in `GetExtensionView.tsx`

thanks! updated resolving your comments
