### PR TITLE
Scroll-to-top

### LINKED ISSUE #226: Firefox: After saving profile, browser doesn't scroll back up
https://stage.rally-web.nonprod.dataops.mozgcp.net/

1. Either sign up for a new account or go to Manage Profile
2. Enter in values in the survey
3. Scroll to the bottom and hit save

https://user-images.githubusercontent.com/444356/189186155-206dde6b-fe20-43c0-af3c-00b74e712f5d.mov

Result: On Firefox, window is still scrolled down to that position, so when studies loads, it is at the bottom.

This occurs when editing the profile information for first time (when creating account) and for any subsequent time (manage profile on existing account).

It works as expected in Chrome

Expect: Window is scrolled back to the top when the studies page loads.

### LINKED ISSUE #237: Current Studies footer list on RWP is incorrect
The list of "Current Studies" in the footer of https://members.rally.mozilla.org/studies is incorrect; it still includes the Facebook Pixel Hunt.

It should match the list on https://rally.mozilla.org/current-studies/ with the FPH moving to "Past Studies"

### LINKED ISSUE #238: Flicker on sign in
image

image

### PR DESCRIPTION
**Pull request by Carla-Moz**
This PR fixes the scroll to the top bug that results after saving the profile. It also updates the footer and fixes the two states flicker problem at login. 

closes #226
closes #237
closes #238

### CODE REVIEW

**Comment by thomik-corp** [comment]
Can we sync from main? I see lot of unrelated changes.

File: web-platform/website/src/components/pages/profile/ProfileButtons.tsx [hunk 1]
```diff
@@ -13,6 +13,15 @@ export function ProfileButtons() {
   const { profileData, isValid } = useProfileData();
   const router = useRouter();
 
+  const goToStudiesPage = () => {
```
Comment (thomik-corp) [inline web-platform/website/src/components/pages/profile/ProfileButtons.tsx]: Suggestion: use function instead of const for stack trace.

File: web-platform/website/src/components/pages/login/EmailSignupView.tsx [hunk 2]
```diff
@@ -94,6 +94,7 @@ export function EmailSignupView() {
       await signupWithEmail(emailRef.current, passwordRef.current);
       await logout();
       setLoginState(LoginState.EmailAccountCreated);
+      debugger
```
Comment (thomik-corp) [inline web-platform/website/src/components/pages/login/EmailSignupView.tsx]: We can revert this.

File: web-platform/website/src/components/pages/login/LoginDataContext.tsx [hunk 3]
```diff
@@ -34,7 +34,7 @@ export function LoginStateProvider(props: { children: React.ReactNode }) {
   useEffect(() => {
     // If user is present but not verified we set initial state to login
     // since login view displays user not verified error.
-    if (isLoaded && user && !isUserVerified) {
+    if (isLoaded && user && !isUserVerified && !LoginState.EmailAccountCreated) {
```
Comment (thomik-corp) [inline web-platform/website/src/components/pages/login/LoginDataContext.tsx]: This is just an enum value and will always be false I believe (! of a defined value). We need to extract the login state via useLoginState I believe and then compare.

File: web-platform/website/src/components/pages/profile/ProfileButtons.tsx [hunk 4]
```diff
@@ -45,11 +49,18 @@ export function ProfileButtons() {
         <Button
           className={`d-flex fw-bold ps-4 pe-4 pt-2 pb-2 ${TertiaryButton}`}
           outline
-          onClick={() => {
+          onClick={async () => {
```
Comment (thomik-corp) [inline web-platform/website/src/components/pages/profile/ProfileButtons.tsx:44]: Async may not be necessary since you are not awaiting anywhere.

File: web-platform/website/src/components/pages/profile/ProfileButtons.tsx [hunk 5]
```diff
@@ -26,17 +26,21 @@ export function ProfileButtons() {
...
+            } me-3`}
           outline={!isValid}
           disabled={!isValid}
           onClick={() => {
             updateUserDocument({
               demographicsData: profileData,
               onboared: true,
             });
-            goToStudiesPage();
+            if (window) {
```
Comment (thomik-corp) [inline web-platform/website/src/components/pages/profile/ProfileButtons.tsx:30]: I believe this is reverted and we will have a function call in the end commit?

File: web-platform/website/src/components/pages/profile/__tests__/ProfileButtons.tests.tsx [hunk 6]
```diff
@@ -55,9 +55,7 @@ describe("ProfileButtons tests", () => {
     expect(push).not.toHaveBeenCalled();
 
     await userEvent.click(cancelButton);
-
-    expect(push).toHaveBeenCalledWith("/");
-
+
```
Comment (thomik-corp) [inline web-platform/website/src/components/pages/profile/__tests__/ProfileButtons.tests.tsx]: We should verify push after awaiting on setTimeout. Maybe we can mock out setTimeout and make it sequential. Same for changes below.

**Review by thomik-corp — COMMENTED** [review]
I will review after rebase from main.

File: web-platform/website/src/components/pages/profile/ProfileButtons.tsx (hunk 4 above)
Comment (Carla-Moz) [reply web-platform/website/src/components/pages/profile/ProfileButtons.tsx:44]: yes forgot to delete it

Comment (Carla-Moz) [reply web-platform/website/src/components/pages/profile/ProfileButtons.tsx:44]: I wouldn't put an async without an await lol

File: web-platform/website/src/components/pages/profile/ProfileButtons.tsx (hunk 5 above)
Comment (Carla-Moz) [reply web-platform/website/src/components/pages/profile/ProfileButtons.tsx:30]: Yes, I removed it. Sorry this was a messy PR. Sigh

File: web-platform/website/src/components/pages/login/EmailSignupView.tsx (hunk 2 above)
Comment (Carla-Moz) [reply web-platform/website/src/components/pages/login/EmailSignupView.tsx]: Yes already removed

File: web-platform/website/src/components/pages/login/LoginDataContext.tsx (hunk 3 above)
Comment (Carla-Moz) [reply web-platform/website/src/components/pages/login/LoginDataContext.tsx]: Yes, I meant to do ``` loginState !== LoginState.SignupWithEmail```

File: web-platform/website/src/components/pages/profile/__tests__/ProfileButtons.tests.tsx (hunk 6 above)
Comment (Carla-Moz) [reply web-platform/website/src/components/pages/profile/__tests__/ProfileButtons.tests.tsx]: I tried mocking setTimeout using jest.useFakeTimers() and jest.setTimeout(time) but neither worked so I just used the setTimeout fn and the test passed. Let me know if you have issues with this.
